package com.drawint.common;

public enum BizExceptionType {
    UNKNOWN_EXCEPTION(0, "UNKNOWN_EXCEPTION"),
    PARAM_MISSING(601, "PARAM_MISSING"),
    USER_ALREADY_EXISTS(602, "USER_ALREADY_EXISTS"),
    METHOD_PARAM_VALIDATE_FAIL(603, "METHOD_PARAM_VALIDATE_FAIL"),
    BEAN_PARAM_VALIDATE_FAIL(604, "BEAN_PARAM_VALIDATE_FAIL"),
    PARAM_BIND_FAIL(605, "PARAM_BIND_FAIL"),
    NULL_RESULT_ERROR(606, "NULL_RESULT_ERROR"),
    LOGIN_AUTH_ERROR(607, "LOGIN_AUTH_ERROR"),
    RELAY_DEVICE_CONTROL_ERROR(608, "RELAY_DEVICE_CONTROL_ERROR"),
    LOGIN_USER_OR_PASSWORD_ERROR(609, "LOGIN_USER_OR_PASSWORD_ERROR"),
    NOT_LOGGED_IN_ERROR(610, "NOT_LOGGED_IN_ERROR"),
    DOOR_CLOSE_FAILED(611, "DOOR_CLOSE_FAILED"),
    DOOR_OPEN_FAILED(612, "DOOR_OPEN_FAILED"),
    MQTT_SEND_ERROR(613, "MQTT_SEND_ERROR"),
    TERMINAL_ACTION_ILLEGAL(614, "TERMINAL_ACTION_ILLEGAL"),
    USER_ACCOUNT_NOT_EXISTS(615, "USER_ACCOUNT_NOT_EXISTS"),
    USER_NOT_EXISTS(616, "USER_NOT_EXISTS"),
    DEFAULT_ACCOUNT_TYPE_USERNAME_ILLEGAL(617, "DEFAULT_ACCOUNT_TYPE_USERNAME_ILLEGAL"),
    TERMINAL_EXISTS(618, "TERMINAL_EXISTS"),
    TERMINAL_NOT_EXISTS(619, "TERMINAL_NOT_EXISTS"),
    TERMINAL_REGISTER_FAILED(620, "TERMINAL_REGISTER_FAILED"),
    TERMINAL_ACTION_NOT_EXISTS(621, "TERMINAL_ACTION_NOT_EXISTS"),
    TERMINAL_ACTION_NO_PERMISSION(622, "TERMINAL_ACTION_NO_PERMISSION"),
    TERMINAL_TYPE_NOT_EXISTS(623, "TERMINAL_TYPE_NOT_EXISTS"),
    TERMINAL_ACTION_NOT_SUPPORTED_YET(624, "TERMINAL_ACTION_NOT_SUPPORTED_YET"),
    ;

    private final Integer code;
    private final String type;

    BizExceptionType(Integer code, String type) {
        this.code = code;
        this.type = type;
    }

    public Integer getCode() {
        return code;
    }

    public String getType() {
        return type;
    }
}
